2025-07-09 13:35:06,829 INFO    MainThread:16 [wandb_setup.py:_flush():76] Current SDK version is 0.15.8
2025-07-09 13:35:06,829 INFO    MainThread:16 [wandb_setup.py:_flush():76] Configure stats pid to 16
2025-07-09 13:35:06,829 INFO    MainThread:16 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2025-07-09 13:35:06,829 INFO    MainThread:16 [wandb_setup.py:_flush():76] Loading settings from /workspace/wandb/settings
2025-07-09 13:35:06,829 INFO    MainThread:16 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-07-09 13:35:06,829 INFO    MainThread:16 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-07-09 13:35:06,829 INFO    MainThread:16 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program': '/workspace/train.py'}
2025-07-09 13:35:06,829 INFO    MainThread:16 [wandb_setup.py:_flush():76] Applying login settings: {'mode': 'offline'}
2025-07-09 13:35:06,830 INFO    MainThread:16 [wandb_init.py:_log_setup():507] Logging user logs to /workspace/wandb/run-20250709_133506-uud50pxn/logs/debug.log
2025-07-09 13:35:06,830 INFO    MainThread:16 [wandb_init.py:_log_setup():508] Logging internal logs to /workspace/wandb/run-20250709_133506-uud50pxn/logs/debug-internal.log
2025-07-09 13:35:06,830 INFO    MainThread:16 [wandb_init.py:init():547] calling init triggers
2025-07-09 13:35:06,830 INFO    MainThread:16 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2025-07-09 13:35:06,830 INFO    MainThread:16 [wandb_init.py:init():596] starting backend
2025-07-09 13:35:06,830 INFO    MainThread:16 [wandb_init.py:init():600] setting up manager
2025-07-09 13:35:06,832 INFO    MainThread:16 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-07-09 13:35:06,834 INFO    MainThread:16 [wandb_init.py:init():606] backend started and connected
2025-07-09 13:35:06,838 INFO    MainThread:16 [wandb_init.py:init():697] updated telemetry
2025-07-09 13:35:06,879 INFO    MainThread:16 [wandb_init.py:init():730] communicating run to backend with 60.0 second timeout
2025-07-09 13:35:07,541 ERROR   MainThread:16 [wandb_init.py:init():756] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2025-07-09 13:35:08,043 ERROR   MainThread:16 [wandb_init.py:init():1165] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/opt/conda/envs/umi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1147, in init
    run = wi.init()
  File "/opt/conda/envs/umi/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 762, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2025-07-09 13:35:09,195 WARNING MsgRouterThr:16 [router.py:message_loop():77] message_loop has been closed
